name: 'Sync content to S3'

on:
  push:
    branches:
      - master
    paths:
      - 'content/**'

jobs:
  sync_content:
    name: 'Sync Content'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Sync to S3'
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl private --follow-symlinks --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_S3_BUCKET: ${{ secrets.BUCKET_NAME }}
          AWS_REGION: 'eu-central-1'
          SOURCE_DIR: 'content'
